/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidopencv_v1_ProcessImage */
#include <android/log.h>
#include "haarcascade_test.hpp"
haarcascade face;


#define APPNAME "MyApp"



#ifndef _Included_com_example_androidopencv_v1_ProcessImage
#define _Included_com_example_androidopencv_v1_ProcessImage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_androidopencv_v1_ProcessImage
 * Method:    run
 * Signature: (II[B[I)I
 */
JNIEXPORT jint JNICALL Java_com_example_androidopencv_1v1_ProcessImage_run
  (JNIEnv *env, jobject obj, jint _width, jint _height, jbyteArray oarray ,jintArray array)
{

	    int width=_width;
	    int height=_height;
	    jbyte *_yuv = env->GetByteArrayElements(oarray, NULL);

	    if(_yuv==NULL)
	    {
		return -1;
	    }

	    jint * _bgra=env->GetIntArrayElements(array,NULL);
	    if(_bgra==NULL)
	    {
		return -1;
	    }
 	    
            Mat myuv(height + height/2, width, CV_8UC1, (unsigned char *)_yuv);
 	    
            Mat mbgra(height, width, CV_8UC4, (unsigned char *)_bgra);
 	    
            cvtColor(myuv, mbgra, CV_YUV420sp2BGR, 4);
 	    //__android_log_print(ANDROID_LOG_ERROR, APPNAME, " 4 ");
            Mat image;
            cvtColor(mbgra,image,CV_BGRA2BGR);
            int flag=face.detect (image);
            cvtColor(image,mbgra,CV_BGR2BGRA);
   	    env->ReleaseByteArrayElements(oarray, _yuv, 0);
	    env->ReleaseIntArrayElements(array, _bgra, 0);

            return flag;
}

/*
 * Class:     com_example_androidopencv_v1_ProcessImage
 * Method:    initDetector
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_androidopencv_1v1_ProcessImage_initDetector
  (JNIEnv * env, jobject obj, jstring javaString)
{
//convert jstring to char*
const char *name = env->GetStringUTFChars(javaString, 0);

// use your string
face=haarcascade((char *)name);

env->ReleaseStringUTFChars(javaString, name);

}

#ifdef __cplusplus
}
#endif
#endif
